### ISSUE TITLE
add SILC (2000 - present)

### ISSUE THREAD

**Issue by fjarlq** [sameroom/history-of-chat#3]
SILC (Secure Internet Live Conferencing) uses its own protocol to provide an IRC-like service with end-to-end encryption and authentication.

SILC never achieved great popularity, and the popularity it did achieve has been declining, but it isn't completely dead yet.
- http://silcnet.org/
- https://web.archive.org/web/20130903163805/http://silcnet.org/general/history.php
- https://en.wikipedia.org/wiki/SILC_(protocol)
- https://github.com/silc/silc

**Comment by abs** [comment]
hi @fjarlq -- we're trying to focus on "services". For example, we don't have "IRC", but we have a few of the bigger networks with "protocol: IRC" comment.

Was there a SILC "service" of significance?

**Comment by fjarlq** [comment]
Ah, I see what you mean... no, I don't believe there ever was a SILC service of significance like that.
